# Generated by Django 5.2.8 on 2025-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichautilizador',
            name='imagem',
            field=models.ImageField(default='defaults/user.png', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichautilizador',
            name='nome',
            field=models.CharField(default='defaults/Luis.png', max_length=100),
            preserve_default=False,
        ),
    ]
