# Generated by Django 5.2.12 on 2026-03-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0002_fichautilizador_imagem_fichautilizador_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichautilizador',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencas.fichautilizador')),
            ],
        ),
    ]
