# Generated by Django 5.2.12 on 2026-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0003_fichautilizador_administrador_presenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenca',
            old_name='data_hora',
            new_name='data_hora_entrada',
        ),
        migrations.AddField(
            model_name='presenca',
            name='data_hora_saida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
