# Generated by Django 5.2.8 on 2026-04-29 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0004_rename_data_hora_presenca_data_hora_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='data_hora_entrada',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='data_hora_saida',
        ),
        migrations.AddField(
            model_name='presenca',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenca',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10),
        ),
    ]
