# Generated by Django 5.2.8 on 2026-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0005_remove_presenca_data_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichautilizador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
